
spring:
  amqp:
    deserialization:
      trust:
        all: true
  rabbitmq:
    host: "${RABBIT_MQ_HOST:localhost}"
    port: "${RABBIT_MQ_PORT:5672}"
    username: "${RABBIT_MQ_USERNAME:admin}"
    password: "${RABBIT_MQ_PASSWORD:admin}"